name: PR Build

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, synchronize, reopened ]

env:
  NODE_VERSION: '18'
  YARN_VERSION: '4.9.2'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            platform: win32
            arch: x64
          - os: windows-latest
            platform: win32
            arch: ia32

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Authenticate with private NPM package for yarn
        run: |
          echo "npmRegistryServer: \"https://registry.npmjs.org\"
          enableGlobalCache: true
          npmRegistries:
            \"//registry.npmjs.org\":
              npmAuthToken: \"${{ secrets.NPM_READ_TOKEN }}\"
              npmAlwaysAuth: true" > ~/.yarnrc.yml

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_READ_TOKEN }}" > ~/.npmrc

      - name: Use NodeJS 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build TypeScript
        run: yarn build:ts

      - name: Build renderer
        run: yarn renderer:build

      - name: Build Electron app
        run: yarn make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: stage
          STAGE_URL: ${{ secrets.STAGE_URL }}
          PROD_URL: ${{ secrets.PROD_URL }}
          CUSTOM_URL: ${{ secrets.CUSTOM_URL }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allen-ui-console-${{ matrix.platform }}-${{ matrix.arch }}-pr-${{ github.event.number }}
          path: |
            out/
            !out/**/*.blockmap
          retention-days: 30

      - name: Create build summary
        if: matrix.os == 'windows-latest' && matrix.arch == 'x64'
        run: |
          echo "## Build Summary for PR #${{ github.event.number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms:** Windows (x64, ia32)" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Status:** ✅ Success" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifacts:** Available for download above" >> $GITHUB_STEP_SUMMARY
          echo "- **Retention:** 30 days" >> $GITHUB_STEP_SUMMARY
