name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0) - leave empty for auto-increment'
        required: false
        type: string
      version_type:
        description: 'Version increment type (patch, minor, major)'
        required: false
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

env:
  NODE_VERSION: '18'
  YARN_VERSION: '4.9.2'

# Cancel in-progress jobs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Check permissions first
  check-permissions:
    runs-on: ubuntu-latest
    outputs:
      has-permissions: ${{ steps.perms.outputs.level }}
    steps:
      - name: Check repository permissions
        id: perms
        uses: actions/github-script@v7
        with:
          script: |
            const { data: permissions } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: context.actor
            });
            core.setOutput('level', permissions.permission);
            console.log(`User ${context.actor} has ${permissions.permission} permission`);

  build:
    runs-on: windows-latest
    timeout-minutes: 45
    # Only run if not a fork and user has write access
    if: |
      github.event_name == 'push' || 
      (github.event_name == 'workflow_dispatch' && 
       !github.event.repository.fork && 
       contains(fromJson('["write", "admin", "maintain"]'), needs.check-permissions.outputs.has-permissions))
    needs: check-permissions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable
        timeout-minutes: 10

      - name: Build TypeScript
        run: yarn build:ts
        timeout-minutes: 5

      - name: Build renderer
        run: yarn renderer:build
        timeout-minutes: 5

      - name: Setup certificates (Windows)
        run: |
          # Create certificates directory
          mkdir -p certificates

          # Decode and create Windows certificate
          if [ "${{ secrets.WINDOWS_CERTIFICATE_BASE64 }}" != "" ]; then
            echo "${{ secrets.WINDOWS_CERTIFICATE_BASE64 }}" | base64 -d > certificates/windows_certificate.pfx
            echo "Windows certificate created"
          fi

          # Set certificate environment variables
          if [ -f "certificates/windows_certificate.pfx" ]; then
            echo "CSC_LINK=certificates/windows_certificate.pfx" >> $GITHUB_ENV
          fi

      - name: Build Electron app (NSIS)
        run: yarn dist:win-installer
        timeout-minutes: 25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          STAGE_URL: ${{ secrets.STAGE_CONSOLE_URL }}
          PROD_URL: ${{ secrets.PROD_CONSOLE_URL }}
          CUSTOM_URL: ${{ secrets.CUSTOM_CONSOLE_URL }}
          CSC_LINK: ${{ env.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Build AppX package
        run: yarn dist:win-appx
        timeout-minutes: 25
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_ENV: production
          STAGE_URL: ${{ secrets.STAGE_CONSOLE_URL }}
          PROD_URL: ${{ secrets.PROD_CONSOLE_URL }}
          CUSTOM_URL: ${{ secrets.CUSTOM_CONSOLE_URL }}
          CSC_LINK: ${{ env.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        timeout-minutes: 5
        with:
          name: allen-ui-console-win32-x64
          path: |
            dist-electron-builder/
            !dist-electron-builder/**/*.blockmap
          retention-days: 90

  version-manager:
    if: |
      github.event_name == 'workflow_dispatch' && 
      github.ref == 'refs/heads/main' && 
      !github.event.repository.fork && 
      contains(fromJson('["write", "admin", "maintain"]'), needs.check-permissions.outputs.has-permissions)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: check-permissions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable
        timeout-minutes: 10

      - name: Get version
        id: get_version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          if [ "${{ github.event.inputs.version }}" != "" ]; then
            # Use manually specified version
            NEW_VERSION="${{ github.event.inputs.version }}"
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "Using manually specified version: $NEW_VERSION"
          else
            # Auto-increment version
            VERSION_TYPE="${{ github.event.inputs.version_type }}"
            if [ "$VERSION_TYPE" = "" ]; then
              VERSION_TYPE="patch"
            fi
            
            # Split version into components
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            
            case $VERSION_TYPE in
              "major")
                NEW_MAJOR=$((MAJOR + 1))
                NEW_VERSION="$NEW_MAJOR.0.0"
                ;;
              "minor")
                NEW_MINOR=$((MINOR + 1))
                NEW_VERSION="$MAJOR.$NEW_MINOR.0"
                ;;
              "patch")
                NEW_PATCH=$((PATCH + 1))
                NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
                ;;
              *)
                NEW_PATCH=$((PATCH + 1))
                NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
                ;;
            esac
            
            echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "Auto-incrementing version: $CURRENT_VERSION -> $NEW_VERSION ($VERSION_TYPE)"
          fi

      - name: Update package.json version
        run: |
          # Update version in package.json
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version
          echo "Updated package.json to version ${{ steps.get_version.outputs.version }}"

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }} [skip ci]"
          git push

  release:
    needs: [build, version-manager]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: |
      (startsWith(github.ref, 'refs/tags/') || 
       (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')) &&
      !github.event.repository.fork &&
      contains(fromJson('["write", "admin", "maintain"]'), needs.check-permissions.outputs.has-permissions)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', needs.version-manager.outputs.version) }}
          name: Release ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', needs.version-manager.outputs.version) }}
          body: |
            ## Allen UI Console Electron ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', needs.version-manager.outputs.version) }}

            ### Downloads
            - **Windows (64-bit):** Installer (.exe)
            - **Windows Store:** AppX Package (.appx) - Ready for Windows Store submission

            ### Build Info
            - **Build Tool:** Electron Builder
            - **Node.js:** 18
            - **Platforms:** Windows 64-bit (NSIS + AppX)
            - **Commit:** ${{ github.sha }}

            ### Windows Store
            The AppX package is ready for submission to the Windows Store. Use the AppX file for:
            - Windows Store publishing
            - Enterprise distribution
            - Testing on Windows 10/11 devices

            ### Changes
            See the [commit history](https://github.com/${{ github.repository }}/compare/${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', needs.version-manager.outputs.version) }}...main) for details.
          files: |
            artifacts/allen-ui-console-win32-x64/dist-electron-builder/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
